name: "GHP Powered"
description: "Solar powered, portable sound system installation for municipal and community events of all sizes."

url: "http://localhost:4000"

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments